//1番
//A
var tokyo = localStorage.getItem('tokutenA5-1');
if (tokyo !== null) {
    $('.tokyo').text(tokyo);
}
var shinjyuku = localStorage.getItem('hazushiA5-1');
$('.shinjyuku').text(shinjyuku);
var ogikubo = localStorage.getItem('tokutenA4-1');
$('.ogikubo').text(ogikubo);
var kunitachi = localStorage.getItem('hazushiA4-1');
$('.kunitachi').text(kunitachi);
var kitijyouji = localStorage.getItem('tokutenA3-1');
$('.kitijyouji').text(kitijyouji);
var sibuya = localStorage.getItem('hazushiA3-1');
$('.sibuya').text(sibuya);
var ome = localStorage.getItem('tokutenA2-1');
$('.ome').text(ome);
var ebisu = localStorage.getItem('hazushiA2-1');
$('.ebisu').text(ebisu);
var yaho = localStorage.getItem('tokutenA1-1');
$('.yaho').text(yaho);
var meidaimae = localStorage.getItem('hazushiA1-1');
$('.meidaimae').text(meidaimae);
//B
var hokkaido = localStorage.getItem('tokutenB5-1');
$('.hokkaido').text(hokkaido);
var niseko = localStorage.getItem('hazushiB5-1');
$('.niseko').text(niseko);
var obihiro = localStorage.getItem('tokutenB4-1');
$('.obihiro').text(obihiro);
var kusiro = localStorage.getItem('hazushiB4-1');
$('.kusiro').text(kusiro);
var wakkanai = localStorage.getItem('tokutenB3-1');
$('.wakkanai').text(wakkanai);
var rusutu = localStorage.getItem('hazushiB3-1');
$('.rusutu').text(rusutu);
var hakodate = localStorage.getItem('tokutenB2-1');
$('.hakodate').text(hakodate);
var ishikari = localStorage.getItem('hazushiB2-1');
$('.ishikari').text(ishikari);
var tokati = localStorage.getItem('tokutenB1-1');
$('.tokati').text(tokati);
var yubari = localStorage.getItem('hazushiB1-1');
$('.yubari').text(yubari);
//C
var aomori = localStorage.getItem('tokutenC5-1');
$('.aomori').text(aomori);
var hatinohe = localStorage.getItem('hazushiC5-1');
$('.hatinohe').text(hatinohe);
var hirosaki = localStorage.getItem('tokutenC4-1');
$('.hirosaki').text(hirosaki);
var towada = localStorage.getItem('hazushiC4-1');
$('.towada').text(towada);
var iwaki = localStorage.getItem('tokutenC3-1');
$('.iwaki').text(iwaki);
var rokkasyo = localStorage.getItem('hazushiC3-1');
$('.rokkasyo').text(rokkasyo);
var nanngou = localStorage.getItem('tokutenC2-1');
$('.nanngou').text(nanngou);
var iwasaki = localStorage.getItem('hazushiC2-1');
$('.iwasaki').text(iwasaki);
var simokita = localStorage.getItem('tokutenC1-1');
$('.simokita').text(simokita);
var rokunohe = localStorage.getItem('hazushiC1-1');
$('.rokunohe').text(rokunohe);
//D
var tiba = localStorage.getItem('tokutenD5-1');
$('.tiba').text(tiba);
var kisarazu = localStorage.getItem('hazushiD5-1');
$('.kisarazu').text(kisarazu);
var kimitu = localStorage.getItem('tokutenD4-1');
$('.kimitu').text(kimitu);
var katusika = localStorage.getItem('hazushiD4-1');
$('.katusika').text(katusika);
var narita = localStorage.getItem('tokutenD3-1');
$('.narita').text(narita);
var simousa = localStorage.getItem('hazushiD3-1');
$('.simousa').text(simousa);
var tyousi = localStorage.getItem('tokutenD2-1');
$('.tyousi').text(tyousi);
var itihara = localStorage.getItem('hazushiD2-1');
$('.itihara').text(itihara);
var wabiko = localStorage.getItem('tokutenD1-1');
$('.wabiko').text(wabiko);
var tateyama = localStorage.getItem('hazushiD1-1');
$('.tateyama').text(tateyama);
//E
var kanagawa = localStorage.getItem('tokutenE5-1');
$('.kanagawa').text(kanagawa);
var yokohama = localStorage.getItem('hazushiE5-1');
$('.yokohama').text(yokohama);
var hakone = localStorage.getItem('tokutenE4-1');
$('.hakone').text(hakone);
var enosima = localStorage.getItem('hazushiE4-1');
$('.enosima').text(enosima);
var sagami = localStorage.getItem('tokutenE3-1');
$('.sagami').text(sagami);
var karuizawa = localStorage.getItem('hazushiE3-1');
$('.karuizawa').text(karuizawa);
var tukimino = localStorage.getItem('tokutenE2-1');
$('.tukimino').text(tukimino);
var azamino = localStorage.getItem('hazushiE2-1');
$('.azamino').text(azamino);
var nagatuta = localStorage.getItem('tokutenE1-1');
$('.nagatuta').text(nagatuta);
var tamapura = localStorage.getItem('hazushiE1-1');
$('.tamapura').text(tamapura);
//F
var okinawa = localStorage.getItem('tokutenF5-1');
$('.okinawa').text(okinawa);
var naha = localStorage.getItem('hazushiF5-1');
$('.naha').text(naha);
var nago = localStorage.getItem('tokutenF4-1');
$('.nago').text(nago);
var itomann = localStorage.getItem('hazushiF4-1');
$('.itomann').text(itomann);
var motobu = localStorage.getItem('tokutenF3-1');
$('.motobu').text(motobu);
var urasoe = localStorage.getItem('hazushiF3-1');
$('.urasoe').text(urasoe);
var ginowann = localStorage.getItem('tokutenF2-1');
$('.ginowann').text(ginowann);
var gishikawa = localStorage.getItem('hazushiF2-1');
$('.gishikawa').text(gishikawa);
var kadena = localStorage.getItem('tokutenF1-1');
$('.kadena').text(kadena);
var ishigaki = localStorage.getItem('hazushiF1-1');
$('.ishigaki').text(ishigaki);


//2番
//A
var tokyo2 = localStorage.getItem('tokutenA5-2');
$('.tokyo2').text(tokyo2);
var shinjyuku2 = localStorage.getItem('hazushiA5-2');
$('.shinjyuku2').text(shinjyuku2);
var ogikubo2 = localStorage.getItem('tokutenA4-2');
$('.ogikubo2').text(ogikubo2);
var kunitachi2 = localStorage.getItem('hazushiA4-2');
$('.kunitachi2').text(kunitachi2);
var kitijyouji2 = localStorage.getItem('tokutenA3-2');
$('.kitijyouji2').text(kitijyouji2);
var sibuya2 = localStorage.getItem('hazushiA3-2');
$('.sibuya2').text(sibuya2);
var ome2 = localStorage.getItem('tokutenA2-2');
$('.ome2').text(ome2);
var ebisu2 = localStorage.getItem('hazushiA2-2');
$('.ebisu2').text(ebisu2);
var yaho2 = localStorage.getItem('tokutenA1-2');
$('.yaho2').text(yaho2);
var meidaimae2 = localStorage.getItem('hazushiA1-2');
$('.meidaimae2').text(meidaimae2);
//B
var hokkaido2 = localStorage.getItem('tokutenB5-2');
$('.hokkaido2').text(hokkaido2);
var niseko2 = localStorage.getItem('hazushiB5-2');
$('.niseko2').text(niseko2);
var obihiro2 = localStorage.getItem('tokutenB4-2');
$('.obihiro2').text(obihiro2);
var kusiro2 = localStorage.getItem('hazushiB4-2');
$('.kusiro2').text(kusiro2);
var wakkanai2 = localStorage.getItem('tokutenB3-2');
$('.wakkanai2').text(wakkanai2);
var rusutu2 = localStorage.getItem('hazushiB3-2');
$('.rusutu2').text(rusutu2);
var hakodate2 = localStorage.getItem('tokutenB2-2');
$('.hakodate2').text(hakodate2);
var ishikari2 = localStorage.getItem('hazushiB2-2');
$('.ishikari2').text(ishikari2);
var tokati2 = localStorage.getItem('tokutenB1-2');
$('.tokati2').text(tokati2);
var yubari2 = localStorage.getItem('hazushiB1-2');
$('.yubari2').text(yubari2);
//C
var aomori2 = localStorage.getItem('tokutenC5-2');
$('.aomori2').text(aomori2);
var hatinohe2 = localStorage.getItem('hazushiC5-2');
$('.hatinohe2').text(hatinohe2);
var hirosaki2 = localStorage.getItem('tokutenC4-2');
$('.hirosaki2').text(hirosaki2);
var towada2 = localStorage.getItem('hazushiC4-2');
$('.towada2').text(towada2);
var iwaki2 = localStorage.getItem('tokutenC3-2');
$('.iwaki2').text(iwaki2);
var rokkasyo2 = localStorage.getItem('hazushiC3-2');
$('.rokkasyo2').text(rokkasyo2);
var nanngou2 = localStorage.getItem('tokutenC2-2');
$('.nanngou2').text(nanngou2);
var iwasaki2 = localStorage.getItem('hazushiC2-2');
$('.iwasaki2').text(iwasaki2);
var simokita2 = localStorage.getItem('tokutenC1-2');
$('.simokita2').text(simokita2);
var rokunohe2 = localStorage.getItem('hazushiC1-2');
$('.rokunohe2').text(rokunohe2);
//D
var tiba2 = localStorage.getItem('tokutenD5-2');
$('.tiba2').text(tiba2);
var kisarazu2 = localStorage.getItem('hazushiD5-2');
$('.kisarazu2').text(kisarazu2);
var kimitu2 = localStorage.getItem('tokutenD4-2');
$('.kimitu2').text(kimitu2);
var katusika2 = localStorage.getItem('hazushiD4-2');
$('.katusika2').text(katusika2);
var narita2 = localStorage.getItem('tokutenD3-2');
$('.narita2').text(narita2);
var simousa2 = localStorage.getItem('hazushiD3-2');
$('.simousa2').text(simousa2);
var tyousi2 = localStorage.getItem('tokutenD2-2');
$('.tyousi2').text(tyousi2);
var itihara2 = localStorage.getItem('hazushiD2-2');
$('.itihara2').text(itihara2);
var wabiko2 = localStorage.getItem('tokutenD1-2');
$('.wabiko2').text(wabiko2);
var tateyama2 = localStorage.getItem('hazushiD1-2');
$('.tateyama2').text(tateyama2);
//E
var kanagawa2 = localStorage.getItem('tokutenE5-2');
$('.kanagawa2').text(kanagawa2);
var yokohama2 = localStorage.getItem('hazushiE5-2');
$('.yokohama2').text(yokohama2);
var hakone2 = localStorage.getItem('tokutenE4-2');
$('.hakone2').text(hakone2);
var enosima2 = localStorage.getItem('hazushiE4-2');
$('.enosima2').text(enosima2);
var sagami2 = localStorage.getItem('tokutenE3-2');
$('.sagami2').text(sagami2);
var karuizawa2 = localStorage.getItem('hazushiE3-2');
$('.karuizawa2').text(karuizawa2);
var tukimino2 = localStorage.getItem('tokutenE2-2');
$('.tukimino2').text(tukimino2);
var azamino2 = localStorage.getItem('hazushiE2-2');
$('.azamino2').text(azamino2);
var nagatuta2 = localStorage.getItem('tokutenE1-2');
$('.nagatuta2').text(nagatuta2);
var tamapura2 = localStorage.getItem('hazushiE1-2');
$('.tamapura2').text(tamapura2);
//F
var okinawa2 = localStorage.getItem('tokutenF5-2');
$('.okinawa2').text(okinawa2);
var naha2 = localStorage.getItem('hazushiF5-2');
$('.naha2').text(naha2);
var nago2 = localStorage.getItem('tokutenF4-2');
$('.nago2').text(nago2);
var itomann2 = localStorage.getItem('hazushiF4-2');
$('.itomann2').text(itomann2);
var motobu2 = localStorage.getItem('tokutenF3-2');
$('.motobu2').text(motobu2);
var urasoe2 = localStorage.getItem('hazushiF3-2');
$('.urasoe2').text(urasoe2);
var ginowann2 = localStorage.getItem('tokutenF2-2');
$('.ginowann2').text(ginowann2);
var gishikawa2 = localStorage.getItem('hazushiF2-2');
$('.gishikawa2').text(gishikawa2);
var kadena2 = localStorage.getItem('tokutenF1-2');
$('.kadena2').text(kadena2);
var ishigaki2 = localStorage.getItem('hazushiF1-2');
$('.ishigaki2').text(ishigaki2);


//3番
//A
var tokyo3 = localStorage.getItem('tokutenA5-3');
$('.tokyo3').text(tokyo3);
var shinjyuku3 = localStorage.getItem('hazushiA5-3');
$('.shinjyuku3').text(shinjyuku3);
var ogikubo3 = localStorage.getItem('tokutenA4-3');
$('.ogikubo3').text(ogikubo3);
var kunitachi3 = localStorage.getItem('hazushiA4-3');
$('.kunitachi3').text(kunitachi3);
var kitijyouji3 = localStorage.getItem('tokutenA3-3');
$('.kitijyouji3').text(kitijyouji3);
var sibuya3 = localStorage.getItem('hazushiA3-3');
$('.sibuya3').text(sibuya3);
var ome3 = localStorage.getItem('tokutenA2-3');
$('.ome3').text(ome3);
var ebisu3 = localStorage.getItem('hazushiA2-3');
$('.ebisu3').text(ebisu3);
var yaho3 = localStorage.getItem('tokutenA1-3');
$('.yaho3').text(yaho3);
var meidaimae3 = localStorage.getItem('hazushiA1-3');
$('.meidaimae3').text(meidaimae3);
//B
var hokkaido3 = localStorage.getItem('tokutenB5-3');
$('.hokkaido3').text(hokkaido3);
var niseko3 = localStorage.getItem('hazushiB5-3');
$('.niseko3').text(niseko3);
var obihiro3 = localStorage.getItem('tokutenB4-3');
$('.obihiro3').text(obihiro3);
var kusiro3 = localStorage.getItem('hazushiB4-3');
$('.kusiro3').text(kusiro3);
var wakkanai3 = localStorage.getItem('tokutenB3-3');
$('.wakkanai3').text(wakkanai3);
var rusutu3 = localStorage.getItem('hazushiB3-3');
$('.rusutu3').text(rusutu3);
var hakodate3 = localStorage.getItem('tokutenB2-3');
$('.hakodate3').text(hakodate3);
var ishikari3 = localStorage.getItem('hazushiB2-3');
$('.ishikari3').text(ishikari3);
var tokati3 = localStorage.getItem('tokutenB1-3');
$('.tokati3').text(tokati3);
var yubari3 = localStorage.getItem('hazushiB1-3');
$('.yubari3').text(yubari3);
//C
var aomori3 = localStorage.getItem('tokutenC5-3');
$('.aomori3').text(aomori3);
var hatinohe3 = localStorage.getItem('hazushiC5-3');
$('.hatinohe3').text(hatinohe3);
var hirosaki3 = localStorage.getItem('tokutenC4-3');
$('.hirosaki3').text(hirosaki3);
var towada3 = localStorage.getItem('hazushiC4-3');
$('.towada3').text(towada3);
var iwaki3 = localStorage.getItem('tokutenC3-3');
$('.iwaki3').text(iwaki3);
var rokkasyo3 = localStorage.getItem('hazushiC3-3');
$('.rokkasyo3').text(rokkasyo3);
var nanngou3 = localStorage.getItem('tokutenC2-3');
$('.nanngou3').text(nanngou3);
var iwasaki3 = localStorage.getItem('hazushiC2-3');
$('.iwasaki3').text(iwasaki3);
var simokita3 = localStorage.getItem('tokutenC1-3');
$('.simokita3').text(simokita3);
var rokunohe3 = localStorage.getItem('hazushiC1-3');
$('.rokunohe3').text(rokunohe3);
//D
var tiba3 = localStorage.getItem('tokutenD5-3');
$('.tiba3').text(tiba3);
var kisarazu3 = localStorage.getItem('hazushiD5-3');
$('.kisarazu3').text(kisarazu3);
var kimitu3 = localStorage.getItem('tokutenD4-3');
$('.kimitu3').text(kimitu3);
var katusika3 = localStorage.getItem('hazushiD4-3');
$('.katusika3').text(katusika3);
var narita3 = localStorage.getItem('tokutenD3-3');
$('.narita3').text(narita3);
var simousa3 = localStorage.getItem('hazushiD3-3');
$('.simousa3').text(simousa3);
var tyousi3 = localStorage.getItem('tokutenD2-3');
$('.tyousi3').text(tyousi3);
var itihara3 = localStorage.getItem('hazushiD2-3');
$('.itihara3').text(itihara3);
var wabiko3 = localStorage.getItem('tokutenD1-3');
$('.wabiko3').text(wabiko3);
var tateyama3 = localStorage.getItem('hazushiD1-3');
$('.tateyama3').text(tateyama3);
//E
var kanagawa3 = localStorage.getItem('tokutenE5-3');
$('.kanagawa3').text(kanagawa3);
var yokohama3 = localStorage.getItem('hazushiE5-3');
$('.yokohama3').text(yokohama3);
var hakone3 = localStorage.getItem('tokutenE4-3');
$('.hakone3').text(hakone3);
var enosima3 = localStorage.getItem('hazushiE4-3');
$('.enosima3').text(enosima3);
var sagami3 = localStorage.getItem('tokutenE3-3');
$('.sagami3').text(sagami3);
var karuizawa3 = localStorage.getItem('hazushiE3-3');
$('.karuizawa3').text(karuizawa3);
var tukimino3 = localStorage.getItem('tokutenE2-3');
$('.tukimino3').text(tukimino3);
var azamino3 = localStorage.getItem('hazushiE2-3');
$('.azamino3').text(azamino3);
var nagatuta3 = localStorage.getItem('tokutenE1-3');
$('.nagatuta3').text(nagatuta3);
var tamapura3 = localStorage.getItem('hazushiE1-3');
$('.tamapura3').text(tamapura3);
//F
var okinawa3 = localStorage.getItem('tokutenF5-3');
$('.okinawa3').text(okinawa3);
var naha3 = localStorage.getItem('hazushiF5-3');
$('.naha3').text(naha3);
var nago3 = localStorage.getItem('tokutenF4-3');
$('.nago3').text(nago3);
var itomann3 = localStorage.getItem('hazushiF4-3');
$('.itomann3').text(itomann3);
var motobu3 = localStorage.getItem('tokutenF3-3');
$('.motobu3').text(motobu3);
var urasoe3 = localStorage.getItem('hazushiF3-3');
$('.urasoe3').text(urasoe3);
var ginowann3 = localStorage.getItem('tokutenF2-3');
$('.ginowann3').text(ginowann3);
var gishikawa3 = localStorage.getItem('hazushiF2-3');
$('.gishikawa3').text(gishikawa3);
var kadena3 = localStorage.getItem('tokutenF1-3');
$('.kadena3').text(kadena3);
var ishigaki3 = localStorage.getItem('hazushiF1-3');
$('.ishigaki3').text(ishigaki3);

//4番
//A
var tokyo4 = localStorage.getItem('tokutenA5-4');
$('.tokyo4').text(tokyo4);
var shinjyuku4 = localStorage.getItem('hazushiA5-4');
$('.shinjyuku4').text(shinjyuku4);
var ogikubo4 = localStorage.getItem('tokutenA4-4');
$('.ogikubo4').text(ogikubo4);
var kunitachi4 = localStorage.getItem('hazushiA4-4');
$('.kunitachi4').text(kunitachi4);
var kitijyouji4 = localStorage.getItem('tokutenA3-4');
$('.kitijyouji4').text(kitijyouji4);
var sibuya4 = localStorage.getItem('hazushiA3-4');
$('.sibuya4').text(sibuya4);
var ome4 = localStorage.getItem('tokutenA2-4');
$('.ome4').text(ome4);
var ebisu4 = localStorage.getItem('hazushiA2-4');
$('.ebisu4').text(ebisu4);
var yaho4 = localStorage.getItem('tokutenA1-4');
$('.yaho4').text(yaho4);
var meidaimae4 = localStorage.getItem('hazushiA1-4');
$('.meidaimae4').text(meidaimae4);
//B
var hokkaido4 = localStorage.getItem('tokutenB5-4');
$('.hokkaido4').text(hokkaido4);
var niseko4 = localStorage.getItem('hazushiB5-4');
$('.niseko4').text(niseko4);
var obihiro4 = localStorage.getItem('tokutenB4-4');
$('.obihiro4').text(obihiro4);
var kusiro4 = localStorage.getItem('hazushiB4-4');
$('.kusiro4').text(kusiro4);
var wakkanai4 = localStorage.getItem('tokutenB3-4');
$('.wakkanai4').text(wakkanai4);
var rusutu4 = localStorage.getItem('hazushiB3-4');
$('.rusutu4').text(rusutu4);
var hakodate4 = localStorage.getItem('tokutenB2-4');
$('.hakodate4').text(hakodate4);
var ishikari4 = localStorage.getItem('hazushiB2-4');
$('.ishikari4').text(ishikari4);
var tokati4 = localStorage.getItem('tokutenB1-4');
$('.tokati4').text(tokati4);
var yubari4 = localStorage.getItem('hazushiB1-4');
$('.yubari4').text(yubari4);
//C
var aomori4 = localStorage.getItem('tokutenC5-4');
$('.aomori4').text(aomori4);
var hatinohe4 = localStorage.getItem('hazushiC5-4');
$('.hatinohe4').text(hatinohe4);
var hirosaki4 = localStorage.getItem('tokutenC4-4');
$('.hirosaki4').text(hirosaki4);
var towada4 = localStorage.getItem('hazushiC4-4');
$('.towada4').text(towada4);
var iwaki4 = localStorage.getItem('tokutenC3-4');
$('.iwaki4').text(iwaki4);
var rokkasyo4 = localStorage.getItem('hazushiC3-4');
$('.rokkasyo4').text(rokkasyo4);
var nanngou4 = localStorage.getItem('tokutenC2-4');
$('.nanngou4').text(nanngou4);
var iwasaki4 = localStorage.getItem('hazushiC2-4');
$('.iwasaki4').text(iwasaki4);
var simokita4 = localStorage.getItem('tokutenC1-4');
$('.simokita4').text(simokita4);
var rokunohe4 = localStorage.getItem('hazushiC1-4');
$('.rokunohe4').text(rokunohe4);
//D
var tiba4 = localStorage.getItem('tokutenD5-4');
$('.tiba4').text(tiba4);
var kisarazu4 = localStorage.getItem('hazushiD5-4');
$('.kisarazu4').text(kisarazu4);
var kimitu4 = localStorage.getItem('tokutenD4-4');
$('.kimitu4').text(kimitu4);
var katusika4 = localStorage.getItem('hazushiD4-4');
$('.katusika4').text(katusika4);
var narita4 = localStorage.getItem('tokutenD3-4');
$('.narita4').text(narita4);
var simousa4 = localStorage.getItem('hazushiD3-4');
$('.simousa4').text(simousa4);
var tyousi4 = localStorage.getItem('tokutenD2-4');
$('.tyousi4').text(tyousi4);
var itihara4 = localStorage.getItem('hazushiD2-4');
$('.itihara4').text(itihara4);
var wabiko4 = localStorage.getItem('tokutenD1-4');
$('.wabiko4').text(wabiko4);
var tateyama4 = localStorage.getItem('hazushiD1-4');
$('.tateyama4').text(tateyama4);
//E
var kanagawa4 = localStorage.getItem('tokutenE5-4');
$('.kanagawa4').text(kanagawa4);
var yokohama4 = localStorage.getItem('hazushiE5-4');
$('.yokohama4').text(yokohama4);
var hakone4 = localStorage.getItem('tokutenE4-4');
$('.hakone4').text(hakone4);
var enosima4 = localStorage.getItem('hazushiE4-4');
$('.enosima4').text(enosima4);
var sagami4 = localStorage.getItem('tokutenE3-4');
$('.sagami4').text(sagami4);
var karuizawa4 = localStorage.getItem('hazushiE3-4');
$('.karuizawa4').text(karuizawa4);
var tukimino4 = localStorage.getItem('tokutenE2-4');
$('.tukimino4').text(tukimino4);
var azamino4 = localStorage.getItem('hazushiE2-4');
$('.azamino4').text(azamino4);
var nagatuta4 = localStorage.getItem('tokutenE1-4');
$('.nagatuta4').text(nagatuta4);
var tamapura4 = localStorage.getItem('hazushiE1-4');
$('.tamapura4').text(tamapura4);
//F
var okinawa4 = localStorage.getItem('tokutenF5-4');
$('.okinawa4').text(okinawa4);
var naha4 = localStorage.getItem('hazushiF5-4');
$('.naha4').text(naha4);
var nago4 = localStorage.getItem('tokutenF4-4');
$('.nago4').text(nago4);
var itomann4 = localStorage.getItem('hazushiF4-4');
$('.itomann4').text(itomann4);
var motobu4 = localStorage.getItem('tokutenF3-4');
$('.motobu4').text(motobu4);
var urasoe4 = localStorage.getItem('hazushiF3-4');
$('.urasoe4').text(urasoe4);
var ginowann4 = localStorage.getItem('tokutenF2-4');
$('.ginowann4').text(ginowann4);
var gishikawa4 = localStorage.getItem('hazushiF2-4');
$('.gishikawa4').text(gishikawa4);
var kadena4 = localStorage.getItem('tokutenF1-4');
$('.kadena4').text(kadena4);
var ishigaki4 = localStorage.getItem('hazushiF1-4');
$('.ishigaki4').text(ishigaki4);


//5番
//A
var tokyo5 = localStorage.getItem('tokutenA5-5');
$('.tokyo5').text(tokyo5);
var shinjyuku5 = localStorage.getItem('hazushiA5-5');
$('.shinjyuku5').text(shinjyuku5);
var ogikubo5 = localStorage.getItem('tokutenA4-5');
$('.ogikubo5').text(ogikubo5);
var kunitachi5 = localStorage.getItem('hazushiA4-5');
$('.kunitachi5').text(kunitachi5);
var kitijyouji5 = localStorage.getItem('tokutenA3-5');
$('.kitijyouji5').text(kitijyouji5);
var sibuya5 = localStorage.getItem('hazushiA3-5');
$('.sibuya5').text(sibuya5);
var ome5 = localStorage.getItem('tokutenA2-5');
$('.ome5').text(ome5);
var ebisu5 = localStorage.getItem('hazushiA2-5');
$('.ebisu5').text(ebisu5);
var yaho5 = localStorage.getItem('tokutenA1-5');
$('.yaho5').text(yaho5);
var meidaimae5 = localStorage.getItem('hazushiA1-5');
$('.meidaimae5').text(meidaimae5);
//B
var hokkaido5 = localStorage.getItem('tokutenB5-5');
$('.hokkaido5').text(hokkaido5);
var niseko5 = localStorage.getItem('hazushiB5-5');
$('.niseko5').text(niseko5);
var obihiro5 = localStorage.getItem('tokutenB4-5');
$('.obihiro5').text(obihiro5);
var kusiro5 = localStorage.getItem('hazushiB4-5');
$('.kusiro5').text(kusiro5);
var wakkanai5 = localStorage.getItem('tokutenB3-5');
$('.wakkanai5').text(wakkanai5);
var rusutu5 = localStorage.getItem('hazushiB3-5');
$('.rusutu5').text(rusutu5);
var hakodate5 = localStorage.getItem('tokutenB2-5');
$('.hakodate5').text(hakodate5);
var ishikari5 = localStorage.getItem('hazushiB2-5');
$('.ishikari5').text(ishikari5);
var tokati5 = localStorage.getItem('tokutenB1-5');
$('.tokati5').text(tokati5);
var yubari5 = localStorage.getItem('hazushiB1-5');
$('.yubari5').text(yubari5);
//C
var aomori5 = localStorage.getItem('tokutenC5-5');
$('.aomori5').text(aomori5);
var hatinohe5 = localStorage.getItem('hazushiC5-5');
$('.hatinohe5').text(hatinohe5);
var hirosaki5 = localStorage.getItem('tokutenC4-5');
$('.hirosaki5').text(hirosaki5);
var towada5 = localStorage.getItem('hazushiC4-5');
$('.towada5').text(towada5);
var iwaki5 = localStorage.getItem('tokutenC3-5');
$('.iwaki5').text(iwaki5);
var rokkasyo5 = localStorage.getItem('hazushiC3-5');
$('.rokkasyo5').text(rokkasyo5);
var nanngou5 = localStorage.getItem('tokutenC2-5');
$('.nanngou5').text(nanngou5);
var iwasaki5 = localStorage.getItem('hazushiC2-5');
$('.iwasaki5').text(iwasaki5);
var simokita5 = localStorage.getItem('tokutenC1-5');
$('.simokita5').text(simokita5);
var rokunohe5 = localStorage.getItem('hazushiC1-5');
$('.rokunohe5').text(rokunohe5);
//D
var tiba5 = localStorage.getItem('tokutenD5-5');
$('.tiba5').text(tiba5);
var kisarazu5 = localStorage.getItem('hazushiD5-5');
$('.kisarazu5').text(kisarazu5);
var kimitu5 = localStorage.getItem('tokutenD4-5');
$('.kimitu5').text(kimitu5);
var katusika5 = localStorage.getItem('hazushiD4-5');
$('.katusika5').text(katusika5);
var narita5 = localStorage.getItem('tokutenD3-5');
$('.narita5').text(narita5);
var simousa5 = localStorage.getItem('hazushiD3-5');
$('.simousa5').text(simousa5);
var tyousi5 = localStorage.getItem('tokutenD2-5');
$('.tyousi5').text(tyousi5);
var itihara5 = localStorage.getItem('hazushiD2-5');
$('.itihara5').text(itihara5);
var wabiko5 = localStorage.getItem('tokutenD1-5');
$('.wabiko5').text(wabiko5);
var tateyama5 = localStorage.getItem('hazushiD1-5');
$('.tateyama5').text(tateyama5);
//E
var kanagawa5 = localStorage.getItem('tokutenE5-5');
$('.kanagawa5').text(kanagawa5);
var yokohama5 = localStorage.getItem('hazushiE5-5');
$('.yokohama5').text(yokohama5);
var hakone5 = localStorage.getItem('tokutenE4-5');
$('.hakone5').text(hakone5);
var enosima5 = localStorage.getItem('hazushiE4-5');
$('.enosima5').text(enosima5);
var sagami5 = localStorage.getItem('tokutenE3-5');
$('.sagami5').text(sagami5);
var karuizawa5 = localStorage.getItem('hazushiE3-5');
$('.karuizawa5').text(karuizawa5);
var tukimino5 = localStorage.getItem('tokutenE2-5');
$('.tukimino5').text(tukimino5);
var azamino5 = localStorage.getItem('hazushiE2-5');
$('.azamino5').text(azamino5);
var nagatuta5 = localStorage.getItem('tokutenE1-5');
$('.nagatuta5').text(nagatuta5);
var tamapura5 = localStorage.getItem('hazushiE1-5');
$('.tamapura5').text(tamapura5);
//F
var okinawa5 = localStorage.getItem('tokutenF5-5');
$('.okinawa5').text(okinawa5);
var naha5 = localStorage.getItem('hazushiF5-5');
$('.naha5').text(naha5);
var nago5 = localStorage.getItem('tokutenF4-5');
$('.nago5').text(nago5);
var itomann5 = localStorage.getItem('hazushiF4-5');
$('.itomann5').text(itomann5);
var motobu5 = localStorage.getItem('tokutenF3-5');
$('.motobu5').text(motobu5);
var urasoe5 = localStorage.getItem('hazushiF3-5');
$('.urasoe5').text(urasoe5);
var ginowann5 = localStorage.getItem('tokutenF2-5');
$('.ginowann5').text(ginowann5);
var gishikawa5 = localStorage.getItem('hazushiF2-5');
$('.gishikawa5').text(gishikawa5);
var kadena5 = localStorage.getItem('tokutenF1-5');
$('.kadena5').text(kadena5);
var ishigaki5 = localStorage.getItem('hazushiF1-5');
$('.ishigaki5').text(ishigaki5);


//6番
//A
var tokyo6 = localStorage.getItem('tokutenA5-6');
$('.tokyo6').text(tokyo6);
var shinjyuku6 = localStorage.getItem('hazushiA5-6');
$('.shinjyuku6').text(shinjyuku6);
var ogikubo6 = localStorage.getItem('tokutenA4-6');
$('.ogikubo6').text(ogikubo6);
var kunitachi6 = localStorage.getItem('hazushiA4-6');
$('.kunitachi6').text(kunitachi6);
var kitijyouji6 = localStorage.getItem('tokutenA3-6');
$('.kitijyouji6').text(kitijyouji6);
var sibuya6 = localStorage.getItem('hazushiA3-6');
$('.sibuya6').text(sibuya6);
var ome6 = localStorage.getItem('tokutenA2-6');
$('.ome6').text(ome6);
var ebisu6 = localStorage.getItem('hazushiA2-6');
$('.ebisu6').text(ebisu6);
var yaho6 = localStorage.getItem('tokutenA1-6');
$('.yaho6').text(yaho6);
var meidaimae6 = localStorage.getItem('hazushiA1-6');
$('.meidaimae6').text(meidaimae6);
//B
var hokkaido6 = localStorage.getItem('tokutenB5-6');
$('.hokkaido6').text(hokkaido6);
var niseko6 = localStorage.getItem('hazushiB5-6');
$('.niseko6').text(niseko6);
var obihiro6 = localStorage.getItem('tokutenB4-6');
$('.obihiro6').text(obihiro6);
var kusiro6 = localStorage.getItem('hazushiB4-6');
$('.kusiro6').text(kusiro6);
var wakkanai6 = localStorage.getItem('tokutenB3-6');
$('.wakkanai6').text(wakkanai6);
var rusutu6 = localStorage.getItem('hazushiB3-6');
$('.rusutu6').text(rusutu6);
var hakodate6 = localStorage.getItem('tokutenB2-6');
$('.hakodate6').text(hakodate6);
var ishikari6 = localStorage.getItem('hazushiB2-6');
$('.ishikari6').text(ishikari6);
var tokati6 = localStorage.getItem('tokutenB1-6');
$('.tokati6').text(tokati6);
var yubari6 = localStorage.getItem('hazushiB1-6');
$('.yubari6').text(yubari6);
//C
var aomori6 = localStorage.getItem('tokutenC5-6');
$('.aomori6').text(aomori6);
var hatinohe6 = localStorage.getItem('hazushiC5-6');
$('.hatinohe6').text(hatinohe6);
var hirosaki6 = localStorage.getItem('tokutenC4-6');
$('.hirosaki6').text(hirosaki6);
var towada6 = localStorage.getItem('hazushiC4-6');
$('.towada6').text(towada6);
var iwaki6 = localStorage.getItem('tokutenC3-6');
$('.iwaki6').text(iwaki6);
var rokkasyo6 = localStorage.getItem('hazushiC3-6');
$('.rokkasyo6').text(rokkasyo6);
var nanngou6 = localStorage.getItem('tokutenC2-6');
$('.nanngou6').text(nanngou6);
var iwasaki6 = localStorage.getItem('hazushiC2-6');
$('.iwasaki6').text(iwasaki6);
var simokita6 = localStorage.getItem('tokutenC1-6');
$('.simokita6').text(simokita6);
var rokunohe6 = localStorage.getItem('hazushiC1-6');
$('.rokunohe6').text(rokunohe6);
//D
var tiba6 = localStorage.getItem('tokutenD5-6');
$('.tiba6').text(tiba6);
var kisarazu6 = localStorage.getItem('hazushiD5-6');
$('.kisarazu6').text(kisarazu6);
var kimitu6 = localStorage.getItem('tokutenD4-6');
$('.kimitu6').text(kimitu6);
var katusika6 = localStorage.getItem('hazushiD4-6');
$('.katusika6').text(katusika6);
var narita6 = localStorage.getItem('tokutenD3-6');
$('.narita6').text(narita6);
var simousa6 = localStorage.getItem('hazushiD3-6');
$('.simousa6').text(simousa6);
var tyousi6 = localStorage.getItem('tokutenD2-6');
$('.tyousi6').text(tyousi6);
var itihara6 = localStorage.getItem('hazushiD2-6');
$('.itihara6').text(itihara6);
var wabiko6 = localStorage.getItem('tokutenD1-6');
$('.wabiko6').text(wabiko6);
var tateyama6 = localStorage.getItem('hazushiD1-6');
$('.tateyama6').text(tateyama6);
//E
var kanagawa6 = localStorage.getItem('tokutenE5-6');
$('.kanagawa6').text(kanagawa6);
var yokohama6 = localStorage.getItem('hazushiE5-6');
$('.yokohama6').text(yokohama6);
var hakone6 = localStorage.getItem('tokutenE4-6');
$('.hakone6').text(hakone6);
var enosima6 = localStorage.getItem('hazushiE4-6');
$('.enosima6').text(enosima6);
var sagami6 = localStorage.getItem('tokutenE3-6');
$('.sagami6').text(sagami6);
var karuizawa6 = localStorage.getItem('hazushiE3-6');
$('.karuizawa6').text(karuizawa6);
var tukimino6 = localStorage.getItem('tokutenE2-6');
$('.tukimino6').text(tukimino6);
var azamino6 = localStorage.getItem('hazushiE2-6');
$('.azamino6').text(azamino6);
var nagatuta6 = localStorage.getItem('tokutenE1-6');
$('.nagatuta6').text(nagatuta6);
var tamapura6 = localStorage.getItem('hazushiE1-6');
$('.tamapura6').text(tamapura6);
//F
var okinawa6 = localStorage.getItem('tokutenF5-6');
$('.okinawa6').text(okinawa6);
var naha6 = localStorage.getItem('hazushiF5-6');
$('.naha6').text(naha6);
var nago6 = localStorage.getItem('tokutenF4-6');
$('.nago6').text(nago6);
var itomann6 = localStorage.getItem('hazushiF4-6');
$('.itomann6').text(itomann6);
var motobu6 = localStorage.getItem('tokutenF3-6');
$('.motobu6').text(motobu6);
var urasoe6 = localStorage.getItem('hazushiF3-6');
$('.urasoe6').text(urasoe6);
var ginowann6 = localStorage.getItem('tokutenF2-6');
$('.ginowann6').text(ginowann6);
var gishikawa6 = localStorage.getItem('hazushiF2-6');
$('.gishikawa6').text(gishikawa6);
var kadena6 = localStorage.getItem('tokutenF1-6');
$('.kadena6').text(kadena6);
var ishigaki6 = localStorage.getItem('hazushiF1-6');
$('.ishigaki6').text(ishigaki6);


//7番
//A
var tokyo7 = localStorage.getItem('tokutenA5-7');
$('.tokyo7').text(tokyo7);
var shinjyuku7 = localStorage.getItem('hazushiA5-7');
$('.shinjyuku7').text(shinjyuku7);
var ogikubo7 = localStorage.getItem('tokutenA4-7');
$('.ogikubo7').text(ogikubo7);
var kunitachi7 = localStorage.getItem('hazushiA4-7');
$('.kunitachi7').text(kunitachi7);
var kitijyouji7 = localStorage.getItem('tokutenA3-7');
$('.kitijyouji7').text(kitijyouji7);
var sibuya7 = localStorage.getItem('hazushiA3-7');
$('.sibuya7').text(sibuya7);
var ome7 = localStorage.getItem('tokutenA2-7');
$('.ome7').text(ome7);
var ebisu7 = localStorage.getItem('hazushiA2-7');
$('.ebisu7').text(ebisu7);
var yaho7 = localStorage.getItem('tokutenA1-7');
$('.yaho7').text(yaho7);
var meidaimae7 = localStorage.getItem('hazushiA1-7');
$('.meidaimae7').text(meidaimae7);
//B
var hokkaido7 = localStorage.getItem('tokutenB5-7');
$('.hokkaido7').text(hokkaido7);
var niseko7 = localStorage.getItem('hazushiB5-7');
$('.niseko7').text(niseko7);
var obihiro7 = localStorage.getItem('tokutenB4-7');
$('.obihiro7').text(obihiro7);
var kusiro7 = localStorage.getItem('hazushiB4-7');
$('.kusiro7').text(kusiro7);
var wakkanai7 = localStorage.getItem('tokutenB3-7');
$('.wakkanai7').text(wakkanai7);
var rusutu7 = localStorage.getItem('hazushiB3-7');
$('.rusutu7').text(rusutu7);
var hakodate7 = localStorage.getItem('tokutenB2-7');
$('.hakodate7').text(hakodate7);
var ishikari7 = localStorage.getItem('hazushiB2-7');
$('.ishikari7').text(ishikari7);
var tokati7 = localStorage.getItem('tokutenB1-7');
$('.tokati7').text(tokati7);
var yubari7 = localStorage.getItem('hazushiB1-7');
$('.yubari7').text(yubari7);
//C
var aomori7 = localStorage.getItem('tokutenC5-7');
$('.aomori7').text(aomori7);
var hatinohe7 = localStorage.getItem('hazushiC5-7');
$('.hatinohe7').text(hatinohe7);
var hirosaki7 = localStorage.getItem('tokutenC4-7');
$('.hirosaki7').text(hirosaki7);
var towada7 = localStorage.getItem('hazushiC4-7');
$('.towada7').text(towada7);
var iwaki7 = localStorage.getItem('tokutenC3-7');
$('.iwaki7').text(iwaki7);
var rokkasyo7 = localStorage.getItem('hazushiC3-7');
$('.rokkasyo7').text(rokkasyo7);
var nanngou7 = localStorage.getItem('tokutenC2-7');
$('.nanngou7').text(nanngou7);
var iwasaki7 = localStorage.getItem('hazushiC2-7');
$('.iwasaki7').text(iwasaki7);
var simokita7 = localStorage.getItem('tokutenC1-7');
$('.simokita7').text(simokita7);
var rokunohe7 = localStorage.getItem('hazushiC1-7');
$('.rokunohe7').text(rokunohe7);
//D
var tiba7 = localStorage.getItem('tokutenD5-7');
$('.tiba7').text(tiba7);
var kisarazu7 = localStorage.getItem('hazushiD5-7');
$('.kisarazu7').text(kisarazu7);
var kimitu7 = localStorage.getItem('tokutenD4-7');
$('.kimitu7').text(kimitu7);
var katusika7 = localStorage.getItem('hazushiD4-7');
$('.katusika7').text(katusika7);
var narita7 = localStorage.getItem('tokutenD3-7');
$('.narita7').text(narita7);
var simousa7 = localStorage.getItem('hazushiD3-7');
$('.simousa7').text(simousa7);
var tyousi7 = localStorage.getItem('tokutenD2-7');
$('.tyousi7').text(tyousi7);
var itihara7 = localStorage.getItem('hazushiD2-7');
$('.itihara7').text(itihara7);
var wabiko7 = localStorage.getItem('tokutenD1-7');
$('.wabiko7').text(wabiko7);
var tateyama7 = localStorage.getItem('hazushiD1-7');
$('.tateyama7').text(tateyama7);
//E
var kanagawa7 = localStorage.getItem('tokutenE5-7');
$('.kanagawa7').text(kanagawa7);
var yokohama7 = localStorage.getItem('hazushiE5-7');
$('.yokohama7').text(yokohama7);
var hakone7 = localStorage.getItem('tokutenE4-7');
$('.hakone7').text(hakone7);
var enosima7 = localStorage.getItem('hazushiE4-7');
$('.enosima7').text(enosima7);
var sagami7 = localStorage.getItem('tokutenE3-7');
$('.sagami7').text(sagami7);
var karuizawa7 = localStorage.getItem('hazushiE3-7');
$('.karuizawa7').text(karuizawa7);
var tukimino7 = localStorage.getItem('tokutenE2-7');
$('.tukimino7').text(tukimino7);
var azamino7 = localStorage.getItem('hazushiE2-7');
$('.azamino7').text(azamino7);
var nagatuta7 = localStorage.getItem('tokutenE1-7');
$('.nagatuta7').text(nagatuta7);
var tamapura7 = localStorage.getItem('hazushiE1-7');
$('.tamapura7').text(tamapura7);
//F
var okinawa7 = localStorage.getItem('tokutenF5-7');
$('.okinawa7').text(okinawa7);
var naha7 = localStorage.getItem('hazushiF5-7');
$('.naha7').text(naha7);
var nago7 = localStorage.getItem('tokutenF4-7');
$('.nago7').text(nago7);
var itomann7 = localStorage.getItem('hazushiF4-7');
$('.itomann7').text(itomann7);
var motobu7 = localStorage.getItem('tokutenF3-7');
$('.motobu7').text(motobu7);
var urasoe7 = localStorage.getItem('hazushiF3-7');
$('.urasoe7').text(urasoe7);
var ginowann7 = localStorage.getItem('tokutenF2-7');
$('.ginowann7').text(ginowann7);
var gishikawa7 = localStorage.getItem('hazushiF2-7');
$('.gishikawa7').text(gishikawa7);
var kadena7 = localStorage.getItem('tokutenF1-7');
$('.kadena7').text(kadena7);
var ishigaki7 = localStorage.getItem('hazushiF1-7');
$('.ishigaki7').text(ishigaki7);


//8番
//A
var tokyo8 = localStorage.getItem('tokutenA5-8');
$('.tokyo8').text(tokyo8);
var shinjyuku8 = localStorage.getItem('hazushiA5-8');
$('.shinjyuku8').text(shinjyuku8);
var ogikubo8 = localStorage.getItem('tokutenA4-8');
$('.ogikubo8').text(ogikubo8);
var kunitachi8 = localStorage.getItem('hazushiA4-8');
$('.kunitachi8').text(kunitachi8);
var kitijyouji8 = localStorage.getItem('tokutenA3-8');
$('.kitijyouji8').text(kitijyouji8);
var sibuya8 = localStorage.getItem('hazushiA3-8');
$('.sibuya8').text(sibuya8);
var ome8 = localStorage.getItem('tokutenA2-8');
$('.ome8').text(ome8);
var ebisu8 = localStorage.getItem('hazushiA2-8');
$('.ebisu8').text(ebisu8);
var yaho8 = localStorage.getItem('tokutenA1-8');
$('.yaho8').text(yaho8);
var meidaimae8 = localStorage.getItem('hazushiA1-8');
$('.meidaimae8').text(meidaimae8);
//B
var hokkaido8 = localStorage.getItem('tokutenB5-8');
$('.hokkaido8').text(hokkaido8);
var niseko8 = localStorage.getItem('hazushiB5-8');
$('.niseko8').text(niseko8);
var obihiro8 = localStorage.getItem('tokutenB4-8');
$('.obihiro8').text(obihiro8);
var kusiro8 = localStorage.getItem('hazushiB4-8');
$('.kusiro8').text(kusiro8);
var wakkanai8 = localStorage.getItem('tokutenB3-8');
$('.wakkanai8').text(wakkanai8);
var rusutu8 = localStorage.getItem('hazushiB3-8');
$('.rusutu8').text(rusutu8);
var hakodate8 = localStorage.getItem('tokutenB2-8');
$('.hakodate8').text(hakodate8);
var ishikari8 = localStorage.getItem('hazushiB2-8');
$('.ishikari8').text(ishikari8);
var tokati8 = localStorage.getItem('tokutenB1-8');
$('.tokati8').text(tokati8);
var yubari8 = localStorage.getItem('hazushiB1-8');
$('.yubari8').text(yubari8);
//C
var aomori8 = localStorage.getItem('tokutenC5-8');
$('.aomori8').text(aomori8);
var hatinohe8 = localStorage.getItem('hazushiC5-8');
$('.hatinohe8').text(hatinohe8);
var hirosaki8 = localStorage.getItem('tokutenC4-8');
$('.hirosaki8').text(hirosaki8);
var towada8 = localStorage.getItem('hazushiC4-8');
$('.towada8').text(towada8);
var iwaki8 = localStorage.getItem('tokutenC3-8');
$('.iwaki8').text(iwaki8);
var rokkasyo8 = localStorage.getItem('hazushiC3-8');
$('.rokkasyo8').text(rokkasyo8);
var nanngou8 = localStorage.getItem('tokutenC2-8');
$('.nanngou8').text(nanngou8);
var iwasaki8 = localStorage.getItem('hazushiC2-8');
$('.iwasaki8').text(iwasaki8);
var simokita8 = localStorage.getItem('tokutenC1-8');
$('.simokita8').text(simokita8);
var rokunohe8 = localStorage.getItem('hazushiC1-8');
$('.rokunohe8').text(rokunohe8);
//D
var tiba8 = localStorage.getItem('tokutenD5-8');
$('.tiba8').text(tiba8);
var kisarazu8 = localStorage.getItem('hazushiD5-8');
$('.kisarazu8').text(kisarazu8);
var kimitu8 = localStorage.getItem('tokutenD4-8');
$('.kimitu8').text(kimitu8);
var katusika8 = localStorage.getItem('hazushiD4-8');
$('.katusika8').text(katusika8);
var narita8 = localStorage.getItem('tokutenD3-8');
$('.narita8').text(narita8);
var simousa8 = localStorage.getItem('hazushiD3-8');
$('.simousa8').text(simousa8);
var tyousi8 = localStorage.getItem('tokutenD2-8');
$('.tyousi8').text(tyousi8);
var itihara8 = localStorage.getItem('hazushiD2-8');
$('.itihara8').text(itihara8);
var wabiko8 = localStorage.getItem('tokutenD1-8');
$('.wabiko8').text(wabiko8);
var tateyama8 = localStorage.getItem('hazushiD1-8');
$('.tateyama8').text(tateyama8);
//E
var kanagawa8 = localStorage.getItem('tokutenE5-8');
$('.kanagawa8').text(kanagawa8);
var yokohama8 = localStorage.getItem('hazushiE5-8');
$('.yokohama8').text(yokohama8);
var hakone8 = localStorage.getItem('tokutenE4-8');
$('.hakone8').text(hakone8);
var enosima8 = localStorage.getItem('hazushiE4-8');
$('.enosima8').text(enosima8);
var sagami8 = localStorage.getItem('tokutenE3-8');
$('.sagami8').text(sagami8);
var karuizawa8 = localStorage.getItem('hazushiE3-8');
$('.karuizawa8').text(karuizawa8);
var tukimino8 = localStorage.getItem('tokutenE2-8');
$('.tukimino8').text(tukimino8);
var azamino8 = localStorage.getItem('hazushiE2-8');
$('.azamino8').text(azamino8);
var nagatuta8 = localStorage.getItem('tokutenE1-8');
$('.nagatuta8').text(nagatuta8);
var tamapura8 = localStorage.getItem('hazushiE1-8');
$('.tamapura8').text(tamapura8);
//F
var okinawa8 = localStorage.getItem('tokutenF5-8');
$('.okinawa8').text(okinawa8);
var naha8 = localStorage.getItem('hazushiF5-8');
$('.naha8').text(naha8);
var nago8 = localStorage.getItem('tokutenF4-8');
$('.nago8').text(nago8);
var itomann8 = localStorage.getItem('hazushiF4-8');
$('.itomann8').text(itomann8);
var motobu8 = localStorage.getItem('tokutenF3-8');
$('.motobu8').text(motobu8);
var urasoe8 = localStorage.getItem('hazushiF3-8');
$('.urasoe8').text(urasoe8);
var ginowann8 = localStorage.getItem('tokutenF2-8');
$('.ginowann8').text(ginowann8);
var gishikawa8 = localStorage.getItem('hazushiF2-8');
$('.gishikawa8').text(gishikawa8);
var kadena8 = localStorage.getItem('tokutenF1-8');
$('.kadena8').text(kadena8);
var ishigaki8 = localStorage.getItem('hazushiF1-8');
$('.ishigaki8').text(ishigaki8);

//9番
//A
var tokyo9 = localStorage.getItem('tokutenA5-9');
$('.tokyo9').text(tokyo9);
var shinjyuku9 = localStorage.getItem('hazushiA5-9');
$('.shinjyuku9').text(shinjyuku9);
var ogikubo9 = localStorage.getItem('tokutenA4-9');
$('.ogikubo9').text(ogikubo9);
var kunitachi9 = localStorage.getItem('hazushiA4-9');
$('.kunitachi9').text(kunitachi9);
var kitijyouji9 = localStorage.getItem('tokutenA3-9');
$('.kitijyouji9').text(kitijyouji9);
var sibuya9 = localStorage.getItem('hazushiA3-9');
$('.sibuya9').text(sibuya9);
var ome9 = localStorage.getItem('tokutenA2-9');
$('.ome9').text(ome9);
var ebisu9 = localStorage.getItem('hazushiA2-9');
$('.ebisu9').text(ebisu9);
var yaho9 = localStorage.getItem('tokutenA1-9');
$('.yaho9').text(yaho9);
var meidaimae9 = localStorage.getItem('hazushiA1-9');
$('.meidaimae9').text(meidaimae9);
//B
var hokkaido9 = localStorage.getItem('tokutenB5-9');
$('.hokkaido9').text(hokkaido9);
var niseko9 = localStorage.getItem('hazushiB5-9');
$('.niseko9').text(niseko9);
var obihiro9 = localStorage.getItem('tokutenB4-9');
$('.obihiro9').text(obihiro9);
var kusiro9 = localStorage.getItem('hazushiB4-9');
$('.kusiro9').text(kusiro9);
var wakkanai9 = localStorage.getItem('tokutenB3-9');
$('.wakkanai9').text(wakkanai9);
var rusutu9 = localStorage.getItem('hazushiB3-9');
$('.rusutu9').text(rusutu9);
var hakodate9 = localStorage.getItem('tokutenB2-9');
$('.hakodate9').text(hakodate9);
var ishikari9 = localStorage.getItem('hazushiB2-9');
$('.ishikari9').text(ishikari9);
var tokati9 = localStorage.getItem('tokutenB1-9');
$('.tokati9').text(tokati9);
var yubari9 = localStorage.getItem('hazushiB1-9');
$('.yubari9').text(yubari9);
//C
var aomori9 = localStorage.getItem('tokutenC5-9');
$('.aomori9').text(aomori9);
var hatinohe9 = localStorage.getItem('hazushiC5-9');
$('.hatinohe9').text(hatinohe9);
var hirosaki9 = localStorage.getItem('tokutenC4-9');
$('.hirosaki9').text(hirosaki9);
var towada9 = localStorage.getItem('hazushiC4-9');
$('.towada9').text(towada9);
var iwaki9 = localStorage.getItem('tokutenC3-9');
$('.iwaki9').text(iwaki9);
var rokkasyo9 = localStorage.getItem('hazushiC3-9');
$('.rokkasyo9').text(rokkasyo9);
var nanngou9 = localStorage.getItem('tokutenC2-9');
$('.nanngou9').text(nanngou9);
var iwasaki9 = localStorage.getItem('hazushiC2-9');
$('.iwasaki9').text(iwasaki9);
var simokita9 = localStorage.getItem('tokutenC1-9');
$('.simokita9').text(simokita9);
var rokunohe9 = localStorage.getItem('hazushiC1-9');
$('.rokunohe9').text(rokunohe9);
//D
var tiba9 = localStorage.getItem('tokutenD5-9');
$('.tiba9').text(tiba9);
var kisarazu9 = localStorage.getItem('hazushiD5-9');
$('.kisarazu9').text(kisarazu9);
var kimitu9 = localStorage.getItem('tokutenD4-9');
$('.kimitu9').text(kimitu9);
var katusika9 = localStorage.getItem('hazushiD4-9');
$('.katusika9').text(katusika9);
var narita9 = localStorage.getItem('tokutenD3-9');
$('.narita9').text(narita9);
var simousa9 = localStorage.getItem('hazushiD3-9');
$('.simousa9').text(simousa9);
var tyousi9 = localStorage.getItem('tokutenD2-9');
$('.tyousi9').text(tyousi9);
var itihara9 = localStorage.getItem('hazushiD2-9');
$('.itihara9').text(itihara9);
var wabiko9 = localStorage.getItem('tokutenD1-9');
$('.wabiko9').text(wabiko9);
var tateyama9 = localStorage.getItem('hazushiD1-9');
$('.tateyama9').text(tateyama9);
//E
var kanagawa9 = localStorage.getItem('tokutenE5-9');
$('.kanagawa9').text(kanagawa9);
var yokohama9 = localStorage.getItem('hazushiE5-9');
$('.yokohama9').text(yokohama9);
var hakone9 = localStorage.getItem('tokutenE4-9');
$('.hakone9').text(hakone9);
var enosima9 = localStorage.getItem('hazushiE4-9');
$('.enosima9').text(enosima9);
var sagami9 = localStorage.getItem('tokutenE3-9');
$('.sagami9').text(sagami9);
var karuizawa9 = localStorage.getItem('hazushiE3-9');
$('.karuizawa9').text(karuizawa9);
var tukimino9 = localStorage.getItem('tokutenE2-9');
$('.tukimino9').text(tukimino9);
var azamino9 = localStorage.getItem('hazushiE2-9');
$('.azamino9').text(azamino9);
var nagatuta9 = localStorage.getItem('tokutenE1-9');
$('.nagatuta9').text(nagatuta9);
var tamapura9 = localStorage.getItem('hazushiE1-9');
$('.tamapura9').text(tamapura9);
//F
var okinawa9 = localStorage.getItem('tokutenF5-9');
$('.okinawa9').text(okinawa9);
var naha9 = localStorage.getItem('hazushiF5-9');
$('.naha9').text(naha9);
var nago9 = localStorage.getItem('tokutenF4-9');
$('.nago9').text(nago9);
var itomann9 = localStorage.getItem('hazushiF4-9');
$('.itomann9').text(itomann9);
var motobu9 = localStorage.getItem('tokutenF3-9');
$('.motobu9').text(motobu9);
var urasoe9 = localStorage.getItem('hazushiF3-9');
$('.urasoe9').text(urasoe9);
var ginowann9 = localStorage.getItem('tokutenF2-9');
$('.ginowann9').text(ginowann9);
var gishikawa9 = localStorage.getItem('hazushiF2-9');
$('.gishikawa9').text(gishikawa9);
var kadena9 = localStorage.getItem('tokutenF1-9');
$('.kadena9').text(kadena9);
var ishigaki9 = localStorage.getItem('hazushiF1-9');
$('.ishigaki9').text(ishigaki9);

//10番
//A
var tokyo10 = localStorage.getItem('tokutenA5-10');
$('.tokyo10').text(tokyo10);
var shinjyuku10 = localStorage.getItem('hazushiA5-10');
$('.shinjyuku10').text(shinjyuku10);
var ogikubo10 = localStorage.getItem('tokutenA4-10');
$('.ogikubo10').text(ogikubo10);
var kunitachi10 = localStorage.getItem('hazushiA4-10');
$('.kunitachi10').text(kunitachi10);
var kitijyouji10 = localStorage.getItem('tokutenA3-10');
$('.kitijyouji10').text(kitijyouji10);
var sibuya10 = localStorage.getItem('hazushiA3-10');
$('.sibuya10').text(sibuya10);
var ome10 = localStorage.getItem('tokutenA2-10');
$('.ome10').text(ome10);
var ebisu10 = localStorage.getItem('hazushiA2-10');
$('.ebisu10').text(ebisu10);
var yaho10 = localStorage.getItem('tokutenA1-10');
$('.yaho10').text(yaho10);
var meidaimae10 = localStorage.getItem('hazushiA1-10');
$('.meidaimae10').text(meidaimae10);
//B
var hokkaido10 = localStorage.getItem('tokutenB5-10');
$('.hokkaido10').text(hokkaido10);
var niseko10 = localStorage.getItem('hazushiB5-10');
$('.niseko10').text(niseko10);
var obihiro10 = localStorage.getItem('tokutenB4-10');
$('.obihiro10').text(obihiro10);
var kusiro10 = localStorage.getItem('hazushiB4-10');
$('.kusiro10').text(kusiro10);
var wakkanai10 = localStorage.getItem('tokutenB3-10');
$('.wakkanai10').text(wakkanai10);
var rusutu10 = localStorage.getItem('hazushiB3-10');
$('.rusutu10').text(rusutu10);
var hakodate10 = localStorage.getItem('tokutenB2-10');
$('.hakodate10').text(hakodate10);
var ishikari10 = localStorage.getItem('hazushiB2-10');
$('.ishikari10').text(ishikari10);
var tokati10 = localStorage.getItem('tokutenB1-10');
$('.tokati10').text(tokati10);
var yubari10 = localStorage.getItem('hazushiB1-10');
$('.yubari10').text(yubari10);
//C
var aomori10 = localStorage.getItem('tokutenC5-10');
$('.aomori10').text(aomori10);
var hatinohe10 = localStorage.getItem('hazushiC5-10');
$('.hatinohe10').text(hatinohe10);
var hirosaki10 = localStorage.getItem('tokutenC4-10');
$('.hirosaki10').text(hirosaki10);
var towada10 = localStorage.getItem('hazushiC4-10');
$('.towada10').text(towada10);
var iwaki10 = localStorage.getItem('tokutenC3-10');
$('.iwaki10').text(iwaki10);
var rokkasyo10 = localStorage.getItem('hazushiC3-10');
$('.rokkasyo10').text(rokkasyo10);
var nanngou10 = localStorage.getItem('tokutenC2-10');
$('.nanngou10').text(nanngou10);
var iwasaki10 = localStorage.getItem('hazushiC2-10');
$('.iwasaki10').text(iwasaki10);
var simokita10 = localStorage.getItem('tokutenC1-10');
$('.simokita10').text(simokita10);
var rokunohe10 = localStorage.getItem('hazushiC1-10');
$('.rokunohe10').text(rokunohe10);
//D
var tiba10 = localStorage.getItem('tokutenD5-10');
$('.tiba10').text(tiba10);
var kisarazu10 = localStorage.getItem('hazushiD5-10');
$('.kisarazu10').text(kisarazu10);
var kimitu10 = localStorage.getItem('tokutenD4-10');
$('.kimitu10').text(kimitu10);
var katusika10 = localStorage.getItem('hazushiD4-10');
$('.katusika10').text(katusika10);
var narita10 = localStorage.getItem('tokutenD3-10');
$('.narita10').text(narita10);
var simousa10 = localStorage.getItem('hazushiD3-10');
$('.simousa10').text(simousa10);
var tyousi10 = localStorage.getItem('tokutenD2-10');
$('.tyousi10').text(tyousi10);
var itihara10 = localStorage.getItem('hazushiD2-10');
$('.itihara10').text(itihara10);
var wabiko10 = localStorage.getItem('tokutenD1-10');
$('.wabiko10').text(wabiko10);
var tateyama10 = localStorage.getItem('hazushiD1-10');
$('.tateyama10').text(tateyama10);
//E
var kanagawa10 = localStorage.getItem('tokutenE5-10');
$('.kanagawa10').text(kanagawa10);
var yokohama10 = localStorage.getItem('hazushiE5-10');
$('.yokohama10').text(yokohama10);
var hakone10 = localStorage.getItem('tokutenE4-10');
$('.hakone10').text(hakone10);
var enosima10 = localStorage.getItem('hazushiE4-10');
$('.enosima10').text(enosima10);
var sagami10 = localStorage.getItem('tokutenE3-10');
$('.sagami10').text(sagami10);
var karuizawa10 = localStorage.getItem('hazushiE3-10');
$('.karuizawa10').text(karuizawa10);
var tukimino10 = localStorage.getItem('tokutenE2-10');
$('.tukimino10').text(tukimino10);
var azamino10 = localStorage.getItem('hazushiE2-10');
$('.azamino10').text(azamino10);
var nagatuta10 = localStorage.getItem('tokutenE1-10');
$('.nagatuta10').text(nagatuta10);
var tamapura10 = localStorage.getItem('hazushiE1-10');
$('.tamapura10').text(tamapura10);
//F
var okinawa10 = localStorage.getItem('tokutenF5-10');
$('.okinawa10').text(okinawa10);
var naha10 = localStorage.getItem('hazushiF5-10');
$('.naha10').text(naha10);
var nago10 = localStorage.getItem('tokutenF4-10');
$('.nago10').text(nago10);
var itomann10 = localStorage.getItem('hazushiF4-10');
$('.itomann10').text(itomann10);
var motobu10 = localStorage.getItem('tokutenF3-10');
$('.motobu10').text(motobu10);
var urasoe10 = localStorage.getItem('hazushiF3-10');
$('.urasoe10').text(urasoe10);
var ginowann10 = localStorage.getItem('tokutenF2-10');
$('.ginowann10').text(ginowann10);
var gishikawa10 = localStorage.getItem('hazushiF2-10');
$('.gishikawa10').text(gishikawa10);
var kadena10 = localStorage.getItem('tokutenF1-10');
$('.kadena10').text(kadena10);
var ishigaki10 = localStorage.getItem('hazushiF1-10');
$('.ishigaki10').text(ishigaki10);


//11番
//A
var tokyo11 = localStorage.getItem('tokutenA5-11');
$('.tokyo11').text(tokyo11);
var shinjyuku11 = localStorage.getItem('hazushiA5-11');
$('.shinjyuku11').text(shinjyuku11);
var ogikubo11 = localStorage.getItem('tokutenA4-11');
$('.ogikubo11').text(ogikubo11);
var kunitachi11 = localStorage.getItem('hazushiA4-11');
$('.kunitachi11').text(kunitachi11);
var kitijyouji11 = localStorage.getItem('tokutenA3-11');
$('.kitijyouji11').text(kitijyouji11);
var sibuya11 = localStorage.getItem('hazushiA3-11');
$('.sibuya11').text(sibuya11);
var ome11 = localStorage.getItem('tokutenA2-11');
$('.ome11').text(ome11);
var ebisu11 = localStorage.getItem('hazushiA2-11');
$('.ebisu11').text(ebisu11);
var yaho11 = localStorage.getItem('tokutenA1-11');
$('.yaho11').text(yaho11);
var meidaimae11 = localStorage.getItem('hazushiA1-11');
$('.meidaimae11').text(meidaimae11);
//B
var hokkaido11 = localStorage.getItem('tokutenB5-11');
$('.hokkaido11').text(hokkaido11);
var niseko11 = localStorage.getItem('hazushiB5-11');
$('.niseko11').text(niseko11);
var obihiro11 = localStorage.getItem('tokutenB4-11');
$('.obihiro11').text(obihiro11);
var kusiro11 = localStorage.getItem('hazushiB4-11');
$('.kusiro11').text(kusiro11);
var wakkanai11 = localStorage.getItem('tokutenB3-11');
$('.wakkanai11').text(wakkanai11);
var rusutu11 = localStorage.getItem('hazushiB3-11');
$('.rusutu11').text(rusutu11);
var hakodate11 = localStorage.getItem('tokutenB2-11');
$('.hakodate11').text(hakodate11);
var ishikari11 = localStorage.getItem('hazushiB2-11');
$('.ishikari11').text(ishikari11);
var tokati11 = localStorage.getItem('tokutenB1-11');
$('.tokati11').text(tokati11);
var yubari11 = localStorage.getItem('hazushiB1-11');
$('.yubari11').text(yubari11);
//C
var aomori11 = localStorage.getItem('tokutenC5-11');
$('.aomori11').text(aomori11);
var hatinohe11 = localStorage.getItem('hazushiC5-11');
$('.hatinohe11').text(hatinohe11);
var hirosaki11 = localStorage.getItem('tokutenC4-11');
$('.hirosaki11').text(hirosaki11);
var towada11 = localStorage.getItem('hazushiC4-11');
$('.towada11').text(towada11);
var iwaki11 = localStorage.getItem('tokutenC3-11');
$('.iwaki11').text(iwaki11);
var rokkasyo11 = localStorage.getItem('hazushiC3-11');
$('.rokkasyo11').text(rokkasyo11);
var nanngou11 = localStorage.getItem('tokutenC2-11');
$('.nanngou11').text(nanngou11);
var iwasaki11 = localStorage.getItem('hazushiC2-11');
$('.iwasaki11').text(iwasaki11);
var simokita11 = localStorage.getItem('tokutenC1-11');
$('.simokita11').text(simokita11);
var rokunohe11 = localStorage.getItem('hazushiC1-11');
$('.rokunohe11').text(rokunohe11);
//D
var tiba11 = localStorage.getItem('tokutenD5-11');
$('.tiba11').text(tiba11);
var kisarazu11 = localStorage.getItem('hazushiD5-11');
$('.kisarazu11').text(kisarazu11);
var kimitu11 = localStorage.getItem('tokutenD4-11');
$('.kimitu11').text(kimitu11);
var katusika11 = localStorage.getItem('hazushiD4-11');
$('.katusika11').text(katusika11);
var narita11 = localStorage.getItem('tokutenD3-11');
$('.narita11').text(narita11);
var simousa11 = localStorage.getItem('hazushiD3-11');
$('.simousa11').text(simousa11);
var tyousi11 = localStorage.getItem('tokutenD2-11');
$('.tyousi11').text(tyousi11);
var itihara11 = localStorage.getItem('hazushiD2-11');
$('.itihara11').text(itihara11);
var wabiko11 = localStorage.getItem('tokutenD1-11');
$('.wabiko11').text(wabiko11);
var tateyama11 = localStorage.getItem('hazushiD1-11');
$('.tateyama11').text(tateyama11);
//E
var kanagawa11 = localStorage.getItem('tokutenE5-11');
$('.kanagawa11').text(kanagawa11);
var yokohama11 = localStorage.getItem('hazushiE5-11');
$('.yokohama11').text(yokohama11);
var hakone11 = localStorage.getItem('tokutenE4-11');
$('.hakone11').text(hakone11);
var enosima11 = localStorage.getItem('hazushiE4-11');
$('.enosima11').text(enosima11);
var sagami11 = localStorage.getItem('tokutenE3-11');
$('.sagami11').text(sagami11);
var karuizawa11 = localStorage.getItem('hazushiE3-11');
$('.karuizawa11').text(karuizawa11);
var tukimino11 = localStorage.getItem('tokutenE2-11');
$('.tukimino11').text(tukimino11);
var azamino11 = localStorage.getItem('hazushiE2-11');
$('.azamino11').text(azamino11);
var nagatuta11 = localStorage.getItem('tokutenE1-11');
$('.nagatuta11').text(nagatuta11);
var tamapura11 = localStorage.getItem('hazushiE1-11');
$('.tamapura11').text(tamapura11);
//F
var okinawa11 = localStorage.getItem('tokutenF5-11');
$('.okinawa11').text(okinawa11);
var naha11 = localStorage.getItem('hazushiF5-11');
$('.naha11').text(naha11);
var nago11 = localStorage.getItem('tokutenF4-11');
$('.nago11').text(nago11);
var itomann11 = localStorage.getItem('hazushiF4-11');
$('.itomann11').text(itomann11);
var motobu11 = localStorage.getItem('tokutenF3-11');
$('.motobu11').text(motobu11);
var urasoe11 = localStorage.getItem('hazushiF3-11');
$('.urasoe11').text(urasoe11);
var ginowann11 = localStorage.getItem('tokutenF2-11');
$('.ginowann11').text(ginowann11);
var gishikawa11 = localStorage.getItem('hazushiF2-11');
$('.gishikawa11').text(gishikawa11);
var kadena11 = localStorage.getItem('tokutenF1-11');
$('.kadena11').text(kadena11);
var ishigaki11 = localStorage.getItem('hazushiF1-11');
$('.ishigaki11').text(ishigaki11);


//12番
//A
var tokyo12 = localStorage.getItem('tokutenA5-12');
$('.tokyo12').text(tokyo12);
var shinjyuku12 = localStorage.getItem('hazushiA5-12');
$('.shinjyuku12').text(shinjyuku12);
var ogikubo12 = localStorage.getItem('tokutenA4-12');
$('.ogikubo12').text(ogikubo12);
var kunitachi12 = localStorage.getItem('hazushiA4-12');
$('.kunitachi12').text(kunitachi12);
var kitijyouji12 = localStorage.getItem('tokutenA3-12');
$('.kitijyouji12').text(kitijyouji12);
var sibuya12 = localStorage.getItem('hazushiA3-12');
$('.sibuya12').text(sibuya12);
var ome12 = localStorage.getItem('tokutenA2-12');
$('.ome12').text(ome12);
var ebisu12 = localStorage.getItem('hazushiA2-12');
$('.ebisu12').text(ebisu12);
var yaho12 = localStorage.getItem('tokutenA1-12');
$('.yaho12').text(yaho12);
var meidaimae12 = localStorage.getItem('hazushiA1-12');
$('.meidaimae12').text(meidaimae12);
//B
var hokkaido12 = localStorage.getItem('tokutenB5-12');
$('.hokkaido12').text(hokkaido12);
var niseko12 = localStorage.getItem('hazushiB5-12');
$('.niseko12').text(niseko12);
var obihiro12 = localStorage.getItem('tokutenB4-12');
$('.obihiro12').text(obihiro12);
var kusiro12 = localStorage.getItem('hazushiB4-12');
$('.kusiro12').text(kusiro12);
var wakkanai12 = localStorage.getItem('tokutenB3-12');
$('.wakkanai12').text(wakkanai12);
var rusutu12 = localStorage.getItem('hazushiB3-12');
$('.rusutu12').text(rusutu12);
var hakodate12 = localStorage.getItem('tokutenB2-12');
$('.hakodate12').text(hakodate12);
var ishikari12 = localStorage.getItem('hazushiB2-12');
$('.ishikari12').text(ishikari12);
var tokati12 = localStorage.getItem('tokutenB1-12');
$('.tokati12').text(tokati12);
var yubari12 = localStorage.getItem('hazushiB1-12');
$('.yubari12').text(yubari12);
//C
var aomori12 = localStorage.getItem('tokutenC5-12');
$('.aomori12').text(aomori12);
var hatinohe12 = localStorage.getItem('hazushiC5-12');
$('.hatinohe12').text(hatinohe12);
var hirosaki12 = localStorage.getItem('tokutenC4-12');
$('.hirosaki12').text(hirosaki12);
var towada12 = localStorage.getItem('hazushiC4-12');
$('.towada12').text(towada12);
var iwaki12 = localStorage.getItem('tokutenC3-12');
$('.iwaki12').text(iwaki12);
var rokkasyo12 = localStorage.getItem('hazushiC3-12');
$('.rokkasyo12').text(rokkasyo12);
var nanngou12 = localStorage.getItem('tokutenC2-12');
$('.nanngou12').text(nanngou12);
var iwasaki12 = localStorage.getItem('hazushiC2-12');
$('.iwasaki12').text(iwasaki12);
var simokita12 = localStorage.getItem('tokutenC1-12');
$('.simokita12').text(simokita12);
var rokunohe12 = localStorage.getItem('hazushiC1-12');
$('.rokunohe12').text(rokunohe12);
//D
var tiba12 = localStorage.getItem('tokutenD5-12');
$('.tiba12').text(tiba12);
var kisarazu12 = localStorage.getItem('hazushiD5-12');
$('.kisarazu12').text(kisarazu12);
var kimitu12 = localStorage.getItem('tokutenD4-12');
$('.kimitu12').text(kimitu12);
var katusika12 = localStorage.getItem('hazushiD4-12');
$('.katusika12').text(katusika12);
var narita12 = localStorage.getItem('tokutenD3-12');
$('.narita12').text(narita12);
var simousa12 = localStorage.getItem('hazushiD3-12');
$('.simousa12').text(simousa12);
var tyousi12 = localStorage.getItem('tokutenD2-12');
$('.tyousi12').text(tyousi12);
var itihara12 = localStorage.getItem('hazushiD2-12');
$('.itihara12').text(itihara12);
var wabiko12 = localStorage.getItem('tokutenD1-12');
$('.wabiko12').text(wabiko12);
var tateyama12 = localStorage.getItem('hazushiD1-12');
$('.tateyama12').text(tateyama12);
//E
var kanagawa12 = localStorage.getItem('tokutenE5-12');
$('.kanagawa12').text(kanagawa12);
var yokohama12 = localStorage.getItem('hazushiE5-12');
$('.yokohama12').text(yokohama12);
var hakone12 = localStorage.getItem('tokutenE4-12');
$('.hakone12').text(hakone12);
var enosima12 = localStorage.getItem('hazushiE4-12');
$('.enosima12').text(enosima12);
var sagami12 = localStorage.getItem('tokutenE3-12');
$('.sagami12').text(sagami12);
var karuizawa12 = localStorage.getItem('hazushiE3-12');
$('.karuizawa12').text(karuizawa12);
var tukimino12 = localStorage.getItem('tokutenE2-12');
$('.tukimino12').text(tukimino12);
var azamino12 = localStorage.getItem('hazushiE2-12');
$('.azamino12').text(azamino12);
var nagatuta12 = localStorage.getItem('tokutenE1-12');
$('.nagatuta12').text(nagatuta12);
var tamapura12 = localStorage.getItem('hazushiE1-12');
$('.tamapura12').text(tamapura12);
//F
var okinawa12 = localStorage.getItem('tokutenF5-12');
$('.okinawa12').text(okinawa12);
var naha12 = localStorage.getItem('hazushiF5-12');
$('.naha12').text(naha12);
var nago12 = localStorage.getItem('tokutenF4-12');
$('.nago12').text(nago12);
var itomann12 = localStorage.getItem('hazushiF4-12');
$('.itomann12').text(itomann12);
var motobu12 = localStorage.getItem('tokutenF3-12');
$('.motobu12').text(motobu12);
var urasoe12 = localStorage.getItem('hazushiF3-12');
$('.urasoe12').text(urasoe12);
var ginowann12 = localStorage.getItem('tokutenF2-12');
$('.ginowann12').text(ginowann12);
var gishikawa12 = localStorage.getItem('hazushiF2-12');
$('.gishikawa12').text(gishikawa12);
var kadena12 = localStorage.getItem('tokutenF1-12');
$('.kadena12').text(kadena12);
var ishigaki12 = localStorage.getItem('hazushiF1-12');
$('.ishigaki12').text(ishigaki12);


//13番
//A
var tokyo13 = localStorage.getItem('tokutenA5-13');
$('.tokyo13').text(tokyo13);
var shinjyuku13 = localStorage.getItem('hazushiA5-13');
$('.shinjyuku13').text(shinjyuku13);
var ogikubo13 = localStorage.getItem('tokutenA4-13');
$('.ogikubo13').text(ogikubo13);
var kunitachi13 = localStorage.getItem('hazushiA4-13');
$('.kunitachi13').text(kunitachi13);
var kitijyouji13 = localStorage.getItem('tokutenA3-13');
$('.kitijyouji13').text(kitijyouji13);
var sibuya13 = localStorage.getItem('hazushiA3-13');
$('.sibuya13').text(sibuya13);
var ome13 = localStorage.getItem('tokutenA2-13');
$('.ome13').text(ome13);
var ebisu13 = localStorage.getItem('hazushiA2-13');
$('.ebisu13').text(ebisu13);
var yaho13 = localStorage.getItem('tokutenA1-13');
$('.yaho13').text(yaho13);
var meidaimae13 = localStorage.getItem('hazushiA1-13');
$('.meidaimae13').text(meidaimae13);
//B
var hokkaido13 = localStorage.getItem('tokutenB5-13');
$('.hokkaido13').text(hokkaido13);
var niseko13 = localStorage.getItem('hazushiB5-13');
$('.niseko13').text(niseko13);
var obihiro13 = localStorage.getItem('tokutenB4-13');
$('.obihiro13').text(obihiro13);
var kusiro13 = localStorage.getItem('hazushiB4-13');
$('.kusiro13').text(kusiro13);
var wakkanai13 = localStorage.getItem('tokutenB3-13');
$('.wakkanai13').text(wakkanai13);
var rusutu13 = localStorage.getItem('hazushiB3-13');
$('.rusutu13').text(rusutu13);
var hakodate13 = localStorage.getItem('tokutenB2-13');
$('.hakodate13').text(hakodate13);
var ishikari13 = localStorage.getItem('hazushiB2-13');
$('.ishikari13').text(ishikari13);
var tokati13 = localStorage.getItem('tokutenB1-13');
$('.tokati13').text(tokati13);
var yubari13 = localStorage.getItem('hazushiB1-13');
$('.yubari13').text(yubari13);
//C
var aomori13 = localStorage.getItem('tokutenC5-13');
$('.aomori13').text(aomori13);
var hatinohe13 = localStorage.getItem('hazushiC5-13');
$('.hatinohe13').text(hatinohe13);
var hirosaki13 = localStorage.getItem('tokutenC4-13');
$('.hirosaki13').text(hirosaki13);
var towada13 = localStorage.getItem('hazushiC4-13');
$('.towada13').text(towada13);
var iwaki13 = localStorage.getItem('tokutenC3-13');
$('.iwaki13').text(iwaki13);
var rokkasyo13 = localStorage.getItem('hazushiC3-13');
$('.rokkasyo13').text(rokkasyo13);
var nanngou13 = localStorage.getItem('tokutenC2-13');
$('.nanngou13').text(nanngou13);
var iwasaki13 = localStorage.getItem('hazushiC2-13');
$('.iwasaki13').text(iwasaki13);
var simokita13 = localStorage.getItem('tokutenC1-13');
$('.simokita13').text(simokita13);
var rokunohe13 = localStorage.getItem('hazushiC1-13');
$('.rokunohe13').text(rokunohe13);
//D
var tiba13 = localStorage.getItem('tokutenD5-13');
$('.tiba13').text(tiba13);
var kisarazu13 = localStorage.getItem('hazushiD5-13');
$('.kisarazu13').text(kisarazu13);
var kimitu13 = localStorage.getItem('tokutenD4-13');
$('.kimitu13').text(kimitu13);
var katusika13 = localStorage.getItem('hazushiD4-13');
$('.katusika13').text(katusika13);
var narita13 = localStorage.getItem('tokutenD3-13');
$('.narita13').text(narita13);
var simousa13 = localStorage.getItem('hazushiD3-13');
$('.simousa13').text(simousa13);
var tyousi13 = localStorage.getItem('tokutenD2-13');
$('.tyousi13').text(tyousi13);
var itihara13 = localStorage.getItem('hazushiD2-13');
$('.itihara13').text(itihara13);
var wabiko13 = localStorage.getItem('tokutenD1-13');
$('.wabiko13').text(wabiko13);
var tateyama13 = localStorage.getItem('hazushiD1-13');
$('.tateyama13').text(tateyama13);
//E
var kanagawa13 = localStorage.getItem('tokutenE5-13');
$('.kanagawa13').text(kanagawa13);
var yokohama13 = localStorage.getItem('hazushiE5-13');
$('.yokohama13').text(yokohama13);
var hakone13 = localStorage.getItem('tokutenE4-13');
$('.hakone13').text(hakone13);
var enosima13 = localStorage.getItem('hazushiE4-13');
$('.enosima13').text(enosima13);
var sagami13 = localStorage.getItem('tokutenE3-13');
$('.sagami13').text(sagami13);
var karuizawa13 = localStorage.getItem('hazushiE3-13');
$('.karuizawa13').text(karuizawa13);
var tukimino13 = localStorage.getItem('tokutenE2-13');
$('.tukimino13').text(tukimino13);
var azamino13 = localStorage.getItem('hazushiE2-13');
$('.azamino13').text(azamino13);
var nagatuta13 = localStorage.getItem('tokutenE1-13');
$('.nagatuta13').text(nagatuta13);
var tamapura13 = localStorage.getItem('hazushiE1-13');
$('.tamapura13').text(tamapura13);
//F
var okinawa13 = localStorage.getItem('tokutenF5-13');
$('.okinawa13').text(okinawa13);
var naha13 = localStorage.getItem('hazushiF5-13');
$('.naha13').text(naha13);
var nago13 = localStorage.getItem('tokutenF4-13');
$('.nago13').text(nago13);
var itomann13 = localStorage.getItem('hazushiF4-13');
$('.itomann13').text(itomann13);
var motobu13 = localStorage.getItem('tokutenF3-13');
$('.motobu13').text(motobu13);
var urasoe13 = localStorage.getItem('hazushiF3-13');
$('.urasoe13').text(urasoe13);
var ginowann13 = localStorage.getItem('tokutenF2-13');
$('.ginowann13').text(ginowann13);
var gishikawa13 = localStorage.getItem('hazushiF2-13');
$('.gishikawa13').text(gishikawa13);
var kadena13 = localStorage.getItem('tokutenF1-13');
$('.kadena13').text(kadena13);
var ishigaki13 = localStorage.getItem('hazushiF1-13');
$('.ishigaki13').text(ishigaki13);

var snow = document.getElementById('snow');
snow.onclick = function () {
    localStorage.clear();
}